language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip3 install combination
# command to run tests
script:
  - python3 tests/test_combination.py
